[build]
  publish = "/"
  command = "pip install -r requirements.txt && python src/bot.py"

[build.environment]
  PYTHON_VERSION = "3.9"

[deploy]
startCommand = "python src/bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PYTHONPATH = "."
